name: Bump Version Number

on:
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    environment: development

    steps:
      - uses: actions/checkout@v1
      # See https://github.com/marketplace/actions/bump-versions
      - name: Bump versions
        uses: remorses/bump-version@js
        with:
            version_file: ./VERSION
            prerelease_tag: dev
        env:
            GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}